In [1]:
# This file contains the group work for Stage 1

In [2]:
# Libraries

import numpy as np
import pandas as pd

Task 3: (50 pts)
Team: (20 pts)
Create a team notebook to read in the COVID-19 data (cases, deaths, and population) using pandas and display the dataframe in a notebook.
Merge all the three variables (cases, deaths, and population) to create a super COVID-19 datafame. Export it to a csv format.

In [3]:
dfCases = pd.read_csv("Data/covid_confirmed_usafacts.csv")
dfDeath = pd.read_csv("Data/covid_deaths_usafacts.csv")
dfPopulation = pd.read_csv("Data/covid_county_population_usafacts.csv")

In [4]:
# Changing display size
pd.set_option('display.max_rows', 500)

In [5]:
dfCases.head(25)

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-07-14,2023-07-15,2023-07-16,2023-07-17,2023-07-18,2023-07-19,2023-07-20,2023-07-21,2023-07-22,2023-07-23
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,19913,19913,19913,19913,19913,19913,19913,19913,19913,19913
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,70521,70521,70521,70521,70521,70521,70521,70521,70521,70521
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,7582,7582,7582,7582,7582,7582,7582,7582,7582,7582
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,8149,8149,8149,8149,8149,8149,8149,8149,8149,8149
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,18872,18872,18872,18872,18872,18872,18872,18872,18872,18872
6,1011,Bullock County,AL,1,0,0,0,0,0,0,...,3057,3057,3057,3057,3057,3057,3057,3057,3057,3057
7,1013,Butler County,AL,1,0,0,0,0,0,0,...,6617,6617,6617,6617,6617,6617,6617,6617,6617,6617
8,1015,Calhoun County,AL,1,0,0,0,0,0,0,...,41931,41931,41931,41931,41931,41931,41931,41931,41931,41931
9,1017,Chambers County,AL,1,0,0,0,0,0,0,...,10935,10935,10935,10935,10935,10935,10935,10935,10935,10935
10,1019,Cherokee County,AL,1,0,0,0,0,0,0,...,6803,6803,6803,6803,6803,6803,6803,6803,6803,6803
11,1021,Chilton County,AL,1,0,0,0,0,0,0,...,13073,13073,13073,13073,13073,13073,13073,13073,13073,13073
12,1023,Choctaw County,AL,1,0,0,0,0,0,0,...,2260,2260,2260,2260,2260,2260,2260,2260,2260,2260
13,1025,Clarke County,AL,1,0,0,0,0,0,0,...,8630,8630,8630,8630,8630,8630,8630,8630,8630,8630
14,1027,Clay County,AL,1,0,0,0,0,0,0,...,5223,5223,5223,5223,5223,5223,5223,5223,5223,5223
15,1029,Cleburne County,AL,1,0,0,0,0,0,0,...,4460,4460,4460,4460,4460,4460,4460,4460,4460,4460
16,1031,Coffee County,AL,1,0,0,0,0,0,0,...,17358,17358,17358,17358,17358,17358,17358,17358,17358,17358
17,1033,Colbert County,AL,1,0,0,0,0,0,0,...,21616,21616,21616,21616,21616,21616,21616,21616,21616,21616
18,1035,Conecuh County,AL,1,0,0,0,0,0,0,...,3654,3654,3654,3654,3654,3654,3654,3654,3654,3654
19,1037,Coosa County,AL,1,0,0,0,0,0,0,...,3805,3805,3805,3805,3805,3805,3805,3805,3805,3805
20,1039,Covington County,AL,1,0,0,0,0,0,0,...,11885,11885,11885,11885,11885,11885,11885,11885,11885,11885
21,1041,Crenshaw County,AL,1,0,0,0,0,0,0,...,4766,4766,4766,4766,4766,4766,4766,4766,4766,4766
22,1043,Cullman County,AL,1,0,0,0,0,0,0,...,31723,31723,31723,31723,31723,31723,31723,31723,31723,31723
23,1045,Dale County,AL,1,0,0,0,0,0,0,...,16715,16715,16715,16715,16715,16715,16715,16715,16715,16715
24,1047,Dallas County,AL,1,0,0,0,0,0,0,...,11099,11099,11099,11099,11099,11099,11099,11099,11099,11099

In [6]:
dfDeath.head(25)

,countyFIPS,County Name,State,StateFIPS,2020-01-22,2020-01-23,2020-01-24,2020-01-25,2020-01-26,2020-01-27,...,2023-07-14,2023-07-15,2023-07-16,2023-07-17,2023-07-18,2023-07-19,2023-07-20,2023-07-21,2023-07-22,2023-07-23
0,0,Statewide Unallocated,AL,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,1,0,0,0,0,0,0,...,235,235,235,235,235,235,235,235,235,235
2,1003,Baldwin County,AL,1,0,0,0,0,0,0,...,731,731,731,731,731,731,731,731,731,731
3,1005,Barbour County,AL,1,0,0,0,0,0,0,...,104,104,104,104,104,104,104,104,104,104
4,1007,Bibb County,AL,1,0,0,0,0,0,0,...,111,111,111,111,111,111,111,111,111,111
5,1009,Blount County,AL,1,0,0,0,0,0,0,...,261,261,261,261,261,261,261,261,261,261
6,1011,Bullock County,AL,1,0,0,0,0,0,0,...,54,54,54,54,54,54,54,54,54,54
7,1013,Butler County,AL,1,0,0,0,0,0,0,...,132,132,132,132,132,132,132,132,132,132
8,1015,Calhoun County,AL,1,0,0,0,0,0,0,...,683,683,683,683,683,683,683,683,683,683
9,1017,Chambers County,AL,1,0,0,0,0,0,0,...,172,172,172,172,172,172,172,172,172,172
10,1019,Cherokee County,AL,1,0,0,0,0,0,0,...,89,89,89,89,89,89,89,89,89,89
11,1021,Chilton County,AL,1,0,0,0,0,0,0,...,221,221,221,221,221,221,221,221,221,221
12,1023,Choctaw County,AL,1,0,0,0,0,0,0,...,39,39,39,39,39,39,39,39,39,39
13,1025,Clarke County,AL,1,0,0,0,0,0,0,...,107,107,107,107,107,107,107,107,107,107
14,1027,Clay County,AL,1,0,0,0,0,0,0,...,94,94,94,94,94,94,94,94,94,94
15,1029,Cleburne County,AL,1,0,0,0,0,0,0,...,73,73,73,73,73,73,73,73,73,73
16,1031,Coffee County,AL,1,0,0,0,0,0,0,...,246,246,246,246,246,246,246,246,246,246
17,1033,Colbert County,AL,1,0,0,0,0,0,0,...,279,279,279,279,279,279,279,279,279,279
18,1035,Conecuh County,AL,1,0,0,0,0,0,0,...,76,76,76,76,76,76,76,76,76,76
19,1037,Coosa County,AL,1,0,0,0,0,0,0,...,64,64,64,64,64,64,64,64,64,64
20,1039,Covington County,AL,1,0,0,0,0,0,0,...,266,266,266,266,266,266,266,266,266,266
21,1041,Crenshaw County,AL,1,0,0,0,0,0,0,...,111,111,111,111,111,111,111,111,111,111
22,1043,Cullman County,AL,1,0,0,0,0,0,0,...,400,400,400,400,400,400,400,400,400,400
23,1045,Dale County,AL,1,0,0,0,0,0,0,...,245,245,245,245,245,245,245,245,245,245
24,1047,Dallas County,AL,1,0,0,0,0,0,0,...,260,260,260,260,260,260,260,260,260,260

In [7]:
dfPopulation.head(25)

    countyFIPS            County Name State  population
0            0  Statewide Unallocated    AL           0
1         1001         Autauga County    AL       55869
2         1003         Baldwin County    AL      223234
3         1005         Barbour County    AL       24686
4         1007            Bibb County    AL       22394
5         1009          Blount County    AL       57826
6         1011         Bullock County    AL       10101
7         1013          Butler County    AL       19448
8         1015         Calhoun County    AL      113605
9         1017        Chambers County    AL       33254
10        1019        Cherokee County    AL       26196
11        1021         Chilton County    AL       44428
12        1023         Choctaw County    AL       12589
13        1025          Clarke County    AL       23622
14        1027            Clay County    AL       13235
15        1029        Cleburne County    AL       14910
16        1031          Coffee County    AL       52342
17        1033         Colbert County    AL       55241
18        1035         Conecuh County    AL       12067
19        1037           Coosa County    AL       10663
20        1039       Covington County    AL       37049
21        1041        Crenshaw County    AL       13772
22        1043         Cullman County    AL       83768
23        1045            Dale County    AL       49172
24        1047          Dallas County    AL       37196

In [8]:
# Both cases and deaths have headers with exact same names - I am going to give them unique header names before merging the 
# data

dfDeath = dfDeath.add_suffix('_Deaths')
dfCases = dfCases.add_suffix('_Cases')

In [14]:
df = pd.concat([dfPopulation, dfCases], axis=1, join="inner")
df = pd.concat([df, dfDeath], axis=1, join="inner")

df.head()

,countyFIPS,County Name,State,population,countyFIPS_Cases,County Name_Cases,State_Cases,StateFIPS_Cases,2020-01-22_Cases,2020-01-23_Cases,...,2023-07-14_Deaths,2023-07-15_Deaths,2023-07-16_Deaths,2023-07-17_Deaths,2023-07-18_Deaths,2023-07-19_Deaths,2023-07-20_Deaths,2023-07-21_Deaths,2023-07-22_Deaths,2023-07-23_Deaths
0,0,Statewide Unallocated,AL,0,0,Statewide Unallocated,AL,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,55869,1001,Autauga County,AL,1,0,0,...,235,235,235,235,235,235,235,235,235,235
2,1003,Baldwin County,AL,223234,1003,Baldwin County,AL,1,0,0,...,731,731,731,731,731,731,731,731,731,731
3,1005,Barbour County,AL,24686,1005,Barbour County,AL,1,0,0,...,104,104,104,104,104,104,104,104,104,104
4,1007,Bibb County,AL,22394,1007,Bibb County,AL,1,0,0,...,111,111,111,111,111,111,111,111,111,111

In [15]:
# Defining a list of columns to drop

to_drop = ['countyFIPS_Cases',
          'County Name_Cases',
          'State_Cases',
          'StateFIPS_Cases',
          'countyFIPS_Deaths',
          'County Name_Deaths',
          'State_Deaths',
          'StateFIPS_Deaths']

# Dropping redundant columns
df.drop(to_drop, inplace = True, axis = 1)

In [16]:
df.head()

,countyFIPS,County Name,State,population,2020-01-22_Cases,2020-01-23_Cases,2020-01-24_Cases,2020-01-25_Cases,2020-01-26_Cases,2020-01-27_Cases,...,2023-07-14_Deaths,2023-07-15_Deaths,2023-07-16_Deaths,2023-07-17_Deaths,2023-07-18_Deaths,2023-07-19_Deaths,2023-07-20_Deaths,2023-07-21_Deaths,2023-07-22_Deaths,2023-07-23_Deaths
0,0,Statewide Unallocated,AL,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1001,Autauga County,AL,55869,0,0,0,0,0,0,...,235,235,235,235,235,235,235,235,235,235
2,1003,Baldwin County,AL,223234,0,0,0,0,0,0,...,731,731,731,731,731,731,731,731,731,731
3,1005,Barbour County,AL,24686,0,0,0,0,0,0,...,104,104,104,104,104,104,104,104,104,104
4,1007,Bibb County,AL,22394,0,0,0,0,0,0,...,111,111,111,111,111,111,111,111,111,111

In [17]:
# Outputing prepared data frame

df.to_csv('ProjectDataStage1.csv')